### ISSUE TITLE
Question regarding uavcan.node.Heartbeat VSSC

### ISSUE THREAD

**Issue by TomDeRybel** [UAVCAN/specification#104]
I was initially working from the alpha-version of the specification. In the Beta version, uavcan.node.Heartbeat VSSC has been reduced to uin8, from uint19 initially. 

Q1: Is this correct?
Q2: Is this now final? I have was going to base an aspect of my implementation on the wider bit size. Now I can still change this.

Best regards,
Tom

**Comment by pavel-kirienko** [comment]
A1: yes

A2: yes

**Comment by TomDeRybel** [comment]
Thanks for the fast reply!
