### ISSUE TITLE
Add a paragraph on standard application capabilities to the introduction

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/specification#22]
Once we have the application parts of the specification completed be sure to add a paragraph on the high-level capabilities this part of the specification provides to section 1.2.

**Comment by pavel-kirienko** [comment]
Is this already addressed by section **1.3 Capabilities**?

**Comment by thirtytwobits** [comment]
I think I'd like to see a feature list of "built-in features" like pnp, register, file transfer, diagnostics, etc. This will help when comparing feature bullet points between protocols.
