### ISSUE TITLE
Final proofreading - grammar, formatting, readability

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/specification#41]
@hamishwillee @mrpollo we are optimistically aiming to finalize the draft next week. What are our chances of getting assistance from Dronecode to get the document proofread and corrected?

**Comment by hamishwillee** [comment]
Hi @pavel-kirienko ,

FYI I no longer directly work for Dronecode, but my management DIUx and Auterion are highly supportive of standards and protocol specification. So I can spend a couple of days on this.
A few points:
1. I find it challenging to do technical editing of specs in one go. If there are any bits of the spec that are known "good to go" then great if you could drip-feed to me. 
2. Xmas is coming. If this drags into next week things get complicated.
Feel free to slack-me with any additional info.

**Comment by pavel-kirienko** [comment]
Okay, thanks, Hamish.

Right now I think nothing is good to go yet because after the missing chapters are finished (see https://github.com/UAVCAN/specification/issues/42) we will go over the doc again and possibly restructure stuff; proofreading probably can't be done until that is finished.

I should post here when we can start proofreading.

**Comment by hamishwillee** [comment]
OK, please do. I'll do my best to review it in a timely manner once it is posted.
