### ISSUE TITLE
Redundant interfaces

### ISSUE THREAD

**Issue by kjetilkjeka** [UAVCAN/specification#8]
@pavel-kirienko I have a couple of questions regarding the redundant interfaces. 
 1. Do we have to require the users to let the first one time out before using the next one. Wouldn't an implementation where the interface where the message is received first on was used and then detection of a lost interface could be done even after the message was received on the "backup" interface.
 2. Do we need every node to use the same interface as number 1. and number 2. If we have nodes that didn't require redundancy wouldn't it be perfectly fine to split them on the two interfaces for load sharing reasons?

**Comment by pavel-kirienko** [comment]
> Do we have to require the users to let the first one time out before using the next one. Wouldn't an implementation where the interface where the message is received first on was used and then detection of a lost interface could be done even after the message was received on the "backup" interface.

Dangerous. The transfer ID wraps around every 32 transfers. Different interfaces are expected to exhibit different latencies even on a properly functioning system, especially if the system shares redundantly-interfaced and non-redundantly-interfaced nodes. If the latency of a backup interface relative to the primary interface exceeds 32*`transfer_interval`, and we were to allow receiving nodes to switch between interfaces freely disregarding the timeout, the receiving node would skip the whole period of transfer ID (32 transfers will be lost). The problem primarily affects low-priority transfers where large latencies are possible.

> Do we need every node to use the same interface as number 1. and number 2. If we have nodes that didn't require redundancy wouldn't it be perfectly fine to split them on the two interfaces for load sharing reasons?

No. Redundant interfaces are there not for load-sharing reasons. Whenever you add a node to the bus you increase the likelihood of its failure, hence the backup bus (-es) should interconnect only mission-critical equipment.

![image](https://user-images.githubusercontent.com/3298404/43633789-eaa76948-9712-11e8-8317-a047a9b779a2.png)
