### ISSUE TITLE
Provide a blue box explaining when it is appropriate to use fixed port-IDs

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/specification#83]

**Comment by TSC21** [comment]
@pavel-kirienko can you provide an ETA for this? This matter is of high urgency and it's a really sensible matter for the Drone SIG. Thanks!

**Comment by pavel-kirienko** [comment]
Addressed in [**The UAVCAN Guide**](uavcan.org/guide/) :book: :mortar_board:
